const bookdata = [
  { title: "The Debacle", author: "Emile Zola", year: "1892" },
  { title: "Lucky Jim", author: "Kingsley Amis", year: "1954" },
  {
    title: "The Bottle Factory Outing",
    author: "Beryl Bainbridge",
    year: "1974",
  },
  { title: "According to Queeney", author: "Beryl Bainbridge", year: "2001" },
  {
    title: "A History of the World in 10 1/2 Chapters",
    author: "Julian Barnes",
    year: "1989",
  },

  { title: "Zuleika Dobson", author: "Max Beerbohm", year: "1911" },
  {
    title: "The Adventures of Augie March",
    author: "Saul Bellow",
    year: "1953",
  },
  { title: "The Uncommon Reader", author: "Alan Bennett", year: "2007" },
  { title: "Queen Lucia", author: "EF Benson", year: "1920" },
  { title: "The Ascent of Rum Doodle", author: "WE Bowman", year: "1956" },
  { title: "The History Man", author: "Malcolm Bradbury", year: "1975" },

  { title: "Illywhacker", author: "Peter Carey", year: "1985" },
  { title: "A Season in Sinji", author: "JL Carr", year: "1967" },
  { title: "The Harpole Report", author: "JL Carr", year: "1972" },
  { title: "The Hearing Trumpet", author: "Leonora Carrington", year: "1974" },
  { title: "Don Quixote", author: "Miguel de Cervantes", year: "1605" },
  {
    title: "The Case of the Gilded Fly",
    author: "Edmund Crispin",
    year: "1944",
  },
  { title: "Just William", author: "Richmal Crompton", year: "1922" },
  { title: "The Pickwick Papers", author: "Charles Dickens" },
  { title: "Martin Chuzzlewit", author: "Charles Dickens" },
  {
    title: "Jacques the Fatalist and his Master",
    author: "Denis Diderot",
    year: "1796",
  },
  { title: "A Fairy Tale of New York", author: "JP Donleavy", year: "1973" },
  { title: "Tom Jones", author: "Henry Fielding" },
  { title: "Bouvard et Pécuchet", author: "Gustave Flaubert", year: "1881" },
  {
    title: "Towards the End of the Morning",
    author: "Michael Frayn",
    year: "1967",
  },
  { title: "Cold Comfort Farm", author: "Stella Gibbons", year: "1932" },
  { title: "Dead Souls", author: "Nikolai Gogol", year: "1842" },
  { title: "Oblomov", author: "Ivan Goncharov", year: "1859" },
  { title: "The Wind in the Willows", author: "Kenneth Grahame", year: "1908" },
  { title: "Travels with My Aunt", author: "Graham Greene", year: "1969" },
  { title: "Diary of a Nobody", author: "George Grossmith", year: "1892" },
  {
    title: "The Curious Incident of the Dog in the Night-time",
    author: "Mark Haddon",
    year: "2003",
  },
  { title: "Catch-22", author: "Joseph Heller", year: "1961" },
  { title: "High Fidelity", author: "Nick Hornby" },
  {
    title: "I Served the King of England",
    author: "Bohumil Hrabal",
    year: "1983",
  },
  {
    title: "Mr Norris Changes Trains",
    author: "Christopher Isherwood",
    year: "1935",
  },
  {
    title: "Pictures from an Institution",
    author: "Randall Jarrell",
    year: "1954",
  },
  { title: "Three Men in a Boat", author: "Jerome K Jerome", year: "1889" },
  { title: "Finnegans Wake", author: "James Joyce", year: "1939" },
  { title: "Lake Wobegon Days", author: "Garrison Keillor", year: "1985" },
  { title: "Death and the Penguin", author: "Andrey Kurkov", year: "1996" },
  { title: "Changing Places", author: "David Lodge", year: "1975" },
  { title: "Nice Work", author: "David Lodge", year: "1988" },
  { title: "The Towers of Trebizond", author: "Rose Macaulay", year: "1956" },
  { title: "England, Their England", author: "AG Macdonell", year: "1933" },
  {
    title: "Cakes and Ale - Or, the Skeleton in the Cupboard",
    author: "W Somerset Maugham",
  },
  { title: "The Restraint of Beasts", author: "Magnus Mills", year: "1998" },
  { title: "Under the Net", author: "Iris Murdoch", year: "1954" },
  { title: "Pnin", author: "Vladimir Nabokov", year: "1957" },
  { title: "Pale Fire", author: "Vladimir Nabokov", year: "1962" },
  {
    title: "The Sacred Book of the Werewolf",
    author: "Victor Pelevin",
    year: "2004",
  },
  { title: "La Disparition", author: "Georges Perec", year: "1969" },

  { title: "Excellent Women", author: "Barbara Pym", year: "1952" },
  { title: "Less Than Angels", author: "Barbara Pym", year: "1955" },

  {
    title: "Solomon Gursky Was Here",
    author: "Mordecai Richler",
    year: "1989",
  },
  { title: "Alms for Oblivion", author: "Simon Raven" },
  { title: "Portnoy’s Complaint", author: "Philip Roth", year: "1969" },
  { title: "Porterhouse Blue", author: "Tom Sharpe", year: "1974" },
  {
    title: "The Adventures of Ferdinand Count Fathom",
    author: "Tobias Smollett",
    year: "1753",
  },
  {
    title: "The Adventures of Roderick Random",
    author: "Tobias Smollett",
    year: "1748",
  },
  {
    title: "The Adventures of Peregrine Pickle",
    author: "Tobias Smollett",
    year: "1751",
  },
  {
    title: "The Expedition of Humphry Clinker",
    author: "Tobias Smollett",
    year: "1771",
  },
  { title: "The Girls of Slender Means", author: "Muriel Spark", year: "1963" },
  { title: "Loitering with Intent", author: "Muriel Spark", year: "1981" },
  { title: "A Far Cry from Kensington", author: "Muriel Spark", year: "1988" },
  {
    title: "The Life and Opinions of Tristram Shandy, Gentleman",
    author: "Laurence Sterne",
    year: "1759",
  },
  { title: "White Man Falling", author: "Mike Stocks", year: "2006" },
  { title: "Handley Cross", author: "RS Surtees" },
  { title: "A Tale of a Tub", author: "Jonathan Swift", year: "1704" },
  { title: "Penrod", author: "Booth Tarkington", year: "1914" },
  { title: "A Confederacy of Dunces", author: "John Kennedy Toole" },
  { title: "Barchester Towers", author: "Anthony Trollope", year: "1857" },
  { title: "Venus on the Half-Shell", author: "Kilgore Trout", year: "1975" },
  { title: "The Mysterious Stranger", author: "Mark Twain", year: "1916" },
  { title: "The Witches of Eastwick", author: "John Updike", year: "1984" },
  { title: "Breakfast of Champions", author: "Kurt Vonnegut", year: "1973" },
  { title: "Infinite Jest", author: "David Foster Wallace", year: "1996" },
  { title: "Decline and Fall", author: "Evelyn Waugh", year: "1928" },
  { title: "Vile Bodies", author: "Evelyn Waugh", year: "1930" },
  { title: "Black Mischief", author: "Evelyn Waugh", year: "1932" },
  { title: "The Loved One", author: "Evelyn Waugh", year: "1948" },
  {
    title: "The Life and Loves of a She-Devil",
    author: "Fay Weldon",
    year: "1983",
  },
  { title: "Tono Bungay", author: "HG Wells", year: "1909" },
  { title: "Anglo-Saxon Attitudes", author: "Angus Wilson", year: "1956" },
  { title: "Something Fresh", author: "PG Wodehouse", year: "1915" },
  { title: "Piccadilly Jim", author: "PG Wodehouse", year: "1917" },
  { title: "The Code of the Woosters", author: "PG Wodehouse", year: "1938" },
  { title: "Epitaph for a Spy", author: "Eric Ambler", year: "1938" },
  { title: "The New York Trilogy", author: "Paul Auster", year: "1987" },
  { title: "The Neon Rain", author: "James Lee Burke", year: "1987" },
  { title: "The Tin Roof Blowdown", author: "James Lee Burke", year: "2007" },
  { title: "The Thirty-Nine Steps", author: "John Buchan", year: "1915" },
  { title: "Greenmantle", author: "John Buchan", year: "1916" },
  { title: "The Postman Always Rings Twice", author: "James M Cain" },
  { title: "The Big Sleep", author: "Raymond Chandler", year: "1939" },
  { title: "The Long Goodbye", author: "Raymond Chandler" },
  {
    title: "And Then There Were None",
    author: "Agatha Christie",
    year: "1939",
  },
  { title: "A Study in Scarlet", author: "Arthur Conan Doyle", year: "1887" },
  {
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    year: "1902",
  },
  { title: "The Manchurian Candidate", author: "Richard Condon", year: "1959" },
  { title: "The Secret Agent", author: "Joseph Conrad", year: "1907" },
  { title: "The Andromeda Strain", author: "Michael Crichton", year: "1969" },
  { title: "Dead Lagoon", author: "Michael Dibdin", year: "1994" },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky", year: "1866" },
  { title: "An American Tragedy", author: "Theodore Dreiser", year: "1925" },
  { title: "My Cousin Rachel", author: "Daphne du Maurier", year: "1951" },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    year: "1844",
  },
  { title: "The Name of the Rose", author: "Umberto Eco", year: "1980" },
  { title: "American Psycho", author: "Bret Easton Ellis", year: "1991" },
  { title: "LA Confidential", author: "James Ellroy", year: "1990" },
  { title: "The Big Nowhere", author: "James Ellroy", year: "1988" },
  { title: "A Quiet Belief in Angels", author: "RJ Ellory", year: "2007" },
  { title: "Casino Royale", author: "Ian Fleming" },
  { title: "The Third Man", author: "Graham Greene" },
  { title: "The King of Torts", author: "John Grisham", year: "2003" },
  { title: "Hangover Square", author: "Patrick Hamilton", year: "1941" },
  { title: "The Maltese Falcon", author: "Dashiell Hammett" },
  { title: "Tourist Season", author: "Carl Hiaasen", year: "1986" },
  {
    title: "The Talented Mr Ripley",
    author: "Patricia Highsmith",
    year: "1955",
  },
  { title: "Bones and Silence", author: "Reginald Hill", year: "1990" },
  { title: "A Rage in Harlem", author: "Chester Himes" },
  { title: "Malice Aforethought", author: "Francis Iles", year: "1931" },
  { title: "Silence of the Grave", author: "Arnadur Indridason", year: "2001" },
  { title: "Misery", author: "Stephen King" },
  { title: "Dolores Claiborne", author: "Stephen King", year: "1992" },
  { title: "Kim", author: "Rudyard Kipling" },
  { title: "The Constant Gardener", author: "John le Carre", year: "2001" },
  {
    title: "Tinker, Tailor, Soldier, Spy",
    author: "John le Carre",
    year: "1974",
  },
  { title: "To Kill a Mockingbird", author: "Harper Lee" },
  { title: "Motherless Brooklyn", author: "Jonathan Lethem" },
  { title: "The Bourne Identity", author: "Robert Ludlum" },
  { title: "Cop Hater", author: "Ed McBain", year: "1956" },
  { title: "No Country for Old Men", author: "Cormac McCarthy" },
  { title: "Enduring Love", author: "Ian McEwan", year: "1997" },
  { title: "Sidetracked", author: "Henning Mankell" },
  { title: "Devil in a Blue Dress", author: "Walter Mosley", year: "1990" },
  { title: "My Name is Red", author: "Orhan Pamuk", year: "1998" },
  { title: "The Big Blowdown", author: "George Pelecanos", year: "1996" },
  { title: "The Godfather", author: "Mario Puzo" },
  { title: "The Crying of Lot 49", author: "Thomas Pynchon" },
  { title: "Exit Music", author: "Ian Rankin", year: "2007" },
  { title: "Judgment in Stone", author: "Ruth Rendell" },
  { title: "Live Flesh", author: "Ruth Rendell", year: "1986" },
  { title: "Murder Must Advertise", author: "Dorothy Le Sayers", year: "1933" },
  { title: "The Madman of Bergerac", author: "Georges Simenon", year: "1932" },
  { title: "Of Mice and Men", author: "John Steinbeck", year: "1937" },
  { title: "The League of Frightened Men", author: "Rex Stout", year: "1935" },
  { title: "The Secret History", author: "Donna Tartt", year: "1992" },
  { title: "The Daughter of Time", author: "Josephine Tey", year: "1951" },
  { title: "Native Son", author: "Richard Wright", year: "1940" },
  { title: "Therese Raquin", author: "Emile Zola", year: "1867" },
  { title: "The Face of Another", author: "Kobo Abe", year: "1964" },
  { title: "Little Women", author: "Louisa May Alcott", year: "1868" },
  {
    title: "Behind the Scenes at the Museum",
    author: "Kate Atkinson",
    year: "1995",
  },
  { title: "Cat’s Eye", author: "Margaret Atwood" },
  { title: "The Crow Road", author: "Iain Banks", year: "1992" },
  { title: "The L Shaped Room", author: "Lynne Reid Banks" },
  { title: "Fun Home", author: "Alison Bechdel" },
  { title: "Malone Dies", author: "Samuel Beckett", year: "1951" },
  { title: "Humboldt’s Gift", author: "Saul Bellow" },
  { title: "The Way of All Flesh", author: "Samuel Butler", year: "1903" },
  { title: "The Outsider", author: "Albert Camus" },
  { title: "Wise Children", author: "Angela Carter", year: "1991" },
  { title: "The Professor’s House", author: "Willa Cather" },
  { title: "The Awakening", author: "Kate Chopin" },
  { title: "Being Dead", author: "Jim Crace", year: "1999" },
  { title: "Great Expectations", author: "Charles Dickens" },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: "1879",
  },
  { title: "My New York Diary", author: "Julie Doucet" },
  { title: "Middlesex", author: "Jeffrey Eugenides" },
  { title: "The Sound and the Fury", author: "William Faulkner", year: "1929" },
  { title: "The Sportswriter", author: "Richard Ford", year: "1986" },
  { title: "Howards End", author: "EM Forster", year: "1910" },
  { title: "The Old Man and the Sea", author: "Ernest Hemingway" },
  { title: "A Prayer for Owen Meany", author: "John Irving", year: "1989" },
  { title: "The Ambassadors", author: "Henry James", year: "1903" },
  { title: "The Unfortunates", author: "BS Johnson", year: "1969" },
  { title: "A Portrait of the Artist as a Young Man", author: "James Joyce" },
  { title: "Ulysses", author: "James Joyce" },
  { title: "One Flew Over the Cuckoo’s Nest", author: "Ken Kesey" },
  { title: "Sons and Lovers", author: "DH Lawrence", year: "1913" },
  { title: "The Golden Notebook", author: "Doris Lessing", year: "1962" },
  { title: "Martin Eden", author: "Jack London", year: "1909" },
  { title: "Under the Volcano", author: "Malcolm Lowry", year: "1947" },
  {
    title: "The Member of the Wedding",
    author: "Carson McCullers",
    year: "1946",
  },
  { title: "Palace Walk", author: "Naguib Mahfouz", year: "1956" },
  { title: "The Bluest Eye", author: "Toni Morrison", year: "1970" },
  { title: "Who Do You Think You Are?", author: "Alice Munro" },
  { title: "The Man Without Qualities", author: "Robert Musil", year: "1930" },
  { title: "A House for Mr Biswas", author: "VS Naipaul" },
  { title: "Teach Us to Outgrow Our Madness", author: "Kezaburo Oe" },
  { title: "The Bell Jar", author: "Sylvia Plath", year: "1963" },
  { title: "My Name Is Asher Lev", author: "Chaim Potok", year: "1972" },
  { title: "The Good Companions", author: "JB Priestley", year: "1929" },
  { title: "The Shipping News", author: "E Annie Proulx", year: "1993" },
  {
    title: "Remembrance of Things Past",
    author: "Marcel Proust",
    year: "1913",
  },

  { title: "The God of Small Things", author: "Arundhati Roy", year: "1997" },
  { title: "The Catcher in the Rye", author: "JD Salinger" },
  { title: "Alberta and Jacob", author: "Cora Sandel" },
  { title: "A Suitable Boy", author: "Vikram Seth", year: "1993" },
  { title: "Unless", author: "Carol Shields", year: "2002" },
  {
    title: "We Need to Talk About Kevin",
    author: "Lionel Shriver",
    year: "2003",
  },
  { title: "A Thousand Acres", author: "Jane Smiley", year: "1991" },
  { title: "On Beauty", author: "Zadie Smith", year: "2005" },
  {
    title: "The Man Who Loved Children",
    author: "Christina Stead",
    year: "1940",
  },
  { title: "East of Eden", author: "John Steinbeck" },
  { title: "Lark Rise to Candleford", author: "Flora Thompson", year: "1945" },
  { title: "The Blackwater Lightship", author: "Colm Toibin", year: "1999" },
  {
    title: "The Secret Diary of Adrian Mole, Aged 13 3/4",
    author: "Sue Townsend",
    year: "1982",
  },
  { title: "Death in Summer", author: "William Trevor", year: "1998" },
  { title: "The Rabbit Omnibus", author: "John Updike" },
  { title: "The Color Purple", author: "Alice Walker", year: "1982" },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
  {
    title: "Oranges Are Not the Only Fruit",
    author: "Jeanette Winterson",
    year: "1985",
  },
  { title: "To the Lighthouse", author: "Virginia Woolf", year: "1927" },
  { title: "Swiss Family Robinson", author: "Johann David Wyss", year: "1812" },
  { title: "Le Grand Meaulnes", author: "Henri Alain-Fournier", year: "1913" },
  { title: "Dom Casmurro Joaquim", author: "Maria Machado de Assis" },
  { title: "Northanger Abbey", author: "Jane Austen", year: "1817" },
  { title: "Sense and Sensibility", author: "Jane Austen", year: "1811" },
  { title: "Pride and Prejudice", author: "Jane Austen", year: "1813" },
  { title: "Mansfield Park", author: "Jane Austen", year: "1814" },
  { title: "Giovanni’s Room", author: "James Baldwin", year: "1956" },
  { title: "Nightwood", author: "Djuna Barnes", year: "1936" },
  { title: "More Die of Heartbreak", author: "Saul Bellow", year: "1987" },
  { title: "Lorna Doone", author: "RD Blackmore" },
  { title: "The Death of the Heart", author: "Elizabeth Bowen", year: "1938" },
  { title: "The Heat of the Day", author: "Elizabeth Bowen", year: "1948" },
  { title: "Jane Eyre", author: "Charlotte Bronte", year: "1847" },
  { title: "Wuthering Heights", author: "Emily Bronte" },
  { title: "Rubyfruit Jungle", author: "Rita Mae Brown", year: "1973" },
  { title: "Breakfast at Tiffany’s", author: "Truman Capote" },
  { title: "Oscar and Lucinda", author: "Peter Carey", year: "1988" },
  { title: "My Antonia", author: "Willa Cather", year: "1918" },
  { title: "Rebecca", author: "Daphne du Maurier" },
  { title: "The Mill on the Floss", author: "George Eliot", year: "1860" },
  { title: "The Virgin Suicides", author: "Jeffrey Eugenides", year: "1993" },
  { title: "The Great Gatsby", author: "F Scott Fitzgerald" },
  { title: "Tender is the Night", author: "F Scott Fitzgerald" },
  { title: "The Blue Flower", author: "Penelope Fitzgerald", year: "1995" },
  { title: "Madame Bovary", author: "Gustave Flaubert", year: "1856" },
  { title: "The Good Soldier", author: "Ford Madox Ford", year: "1915" },
  { title: "A Room with a View", author: "EM Forster", year: "1908" },
  { title: "The French Lieutenant’s Woman", author: "John Fowles" },
  { title: "The Snow Goose", author: "Paul Gallico" },
  {
    title: "The Sorrows of Young Werther",
    author: "Johann Wolfgang Goethe",
    year: "1774",
  },
  { title: "Far From the Madding Crowd", author: "Thomas Hardy", year: "1874" },
  { title: "Tess of the D’Urbervilles", author: "Thomas Hardy" },
  { title: "The Scarlet Letter", author: "Nathaniel Hawthorne", year: "1850" },
  { title: "The Transit of Venus", author: "Shirley Hazzard", year: "1980" },
  {
    title: "Their Eyes Were Watching God",
    author: "Zora Neale Hurston",
    year: "1937",
  },
  { title: "The Remains of the Day", author: "Kazuo Ishiguro", year: "1989" },
  { title: "Portrait of a Lady", author: "Henry James", year: "1881" },
  { title: "The Wings of the Dove", author: "Henry James", year: "1902" },
  { title: "Zorba the Greek", author: "Nikos Kazantzakis" },
  {
    title: "The Book of Laughter and Forgetting",
    author: "Milan Kundera",
    year: "1979",
  },
  {
    title: "The Unbearable Lightness of Being",
    author: "Milan Kundera",
    year: "1984",
  },
  { title: "Lady Chatterley’s Lover", author: "DH Lawrence", year: "1126" },
  { title: "Zami", author: "Audre Lorde" },
  { title: "Death in Venice", author: "Thomas Mann", year: "1912" },
  { title: "A Heart So White", author: "Javier Marias", year: "1992" },
  {
    title: "Love in the Time of Cholera",
    author: "Gabriel Garcia Marquez",
    year: "1985",
  },
  { title: "Of Human Bondage", author: "Somerset Maugham", year: "1915" },
  { title: "So Long, See you Tomorrow", author: "William Maxwell" },
  {
    title: "The Heart is a Lonely Hunter",
    author: "Carson McCullers",
    year: "1940",
  },
  { title: "Atonement", author: "Ian McEwan" },
  { title: "Tropic of Cancer", author: "Henry Miller" },
  { title: "Gone With the Wind", author: "Margaret Mitchell" },
  { title: "The Pursuit of Love", author: "Nancy Mitford", year: "1945" },
  { title: "Love in a Cold Climate", author: "Nancy Mitford" },

  { title: "Norwegian Wood", author: "Haruki Murakami" },
  {
    title: "Lolita, or the Confessions of a White Widowed Male",
    author: "Vladimir Nabokov",
  },
  { title: "The Painter of Signs", author: "RK Narayan", year: "1977" },
  { title: "Delta of Venus", author: "Anais Nin", year: "1977" },
  { title: "The English Patient", author: "Michael Ondaatje", year: "1992" },
  { title: "Doctor Zhivago", author: "Boris Pasternak" },
  { title: "Manon Lescaut", author: "Abbe Prevost", year: "1731" },
  { title: "Wide Sargasso Sea", author: "Jean Rhys", year: "1966" },
  { title: "Clarissa", author: "Samuel Richardson", year: "1748" },
  { title: "Gilead", author: "Marilynne Robinson" },
  { title: "Bonjour Tristesse", author: "Francoise Sagan", year: "1954" },
  { title: "The Reader", author: "Bernhard Schlink", year: "1995" },
  {
    title: "By Grand Central Station I Sat Down and Wept",
    author: "Elizabeth Smart",
    year: "1945",
  },
  { title: "I Capture the Castle", author: "Dodie Smith", year: "1948" },
  { title: "The Map of Love", author: "Ahdaf Soueif" },
  { title: "Valley of the Dolls", author: "Jacqueline Susann" },
  { title: "Diary of a Mad Old Man", author: "Junichiro Tanizaki" },
  { title: "Anna Karenina", author: "Leo Tolstoy", year: "1878" },
  { title: "Breathing Lessons", author: "Anne Tyler", year: "1988" },
  { title: "The Accidental Tourist", author: "Anne Tyler", year: "1985" },
  { title: "The Age of Innocence", author: "Edith Wharton", year: "1920" },
  { title: "Revolutionary Road", author: "Richard Yates", year: "1961" },
  { title: "The Hitchhikers Guide to the Galaxy", author: "Douglas Adams" },
  { title: "Foundation", author: "Isaac Asimov" },
  { title: "The Blind Assassin", author: "Margaret Atwood", year: "2000" },
  { title: "The Handmaid’s Tale", author: "Margaret Atwood", year: "1985" },
  {
    title: "In the Country of Last Things",
    author: "Paul Auster",
    year: "1987",
  },
  { title: "The Drowned World", author: "JG Ballard", year: "1962" },
  { title: "Crash", author: "JG Ballard" },
  { title: "Millennium People", author: "JG Ballard" },
  { title: "The Wasp Factory", author: "Iain Banks", year: "1984" },
  { title: "Consider Phlebas", author: "Iain M Banks", year: "1987" },
  { title: "Weaveworld", author: "Clive Barker", year: "1987" },
  { title: "Darkmans", author: "Nicola Barker" },
  { title: "Vathek", author: "William Beckford", year: "1786" },
  { title: "The Stars My Destination", author: "Alfred Bester", year: "1956" },
  { title: "Fahrenheit 451", author: "Ray Bradbury" },
  { title: "Rogue Moon", author: "Algis Budrys", year: "1960" },
  {
    title: "The Master and Margarita",
    author: "Mikhail Bulgakov",
    year: "1966",
  },
  { title: "The Coming Race", author: "EGEL Bulwer-Lytton", year: "1871" },
  { title: "A Clockwork Orange", author: "Anthony Burgess" },
  { title: "A Princess of Mars", author: "Edgar Rice Burroughs", year: "1912" },
  { title: "Naked Lunch", author: "William Burroughs", year: "1959" },
  { title: "Kindred", author: "Octavia Butler" },
  { title: "Erewhon", author: "Samuel Butler", year: "1872" },
  { title: "The Baron in the Trees", author: "Italo Calvino" },
  {
    title: "Alice’s Adventures in Wonderland",
    author: "Lewis Carroll",
    year: "1865",
  },
  {
    title: "Through the Looking Glass and What Alice Found There",
    author: "Lewis Carroll",
    year: "1871",
  },
  {
    title: "The Amazing Adventures of Kavalier and Clay",
    author: "Michael Chabon",
    year: "2000",
  },
  { title: "The Man who was Thursday", author: "GK Chesterton" },
  { title: "Childhood’s End", author: "Arthur C Clarke" },
  {
    title: "Jonathan Strange & Mr Norrell",
    author: "Susanna Clarke",
    year: "1126",
  },
  { title: "Hello Summer, Goodbye", author: "Michael G Coney", year: "1975" },
  { title: "House of Leaves", author: "Mark Danielewski", year: "2000" },
  {
    title: "Do Androids Dream of Electric Sheep?",
    author: "Philip K Dick",
    year: "1968",
  },
  { title: "American Gods", author: "Neil Gaiman", year: "2001" },
  { title: "Neuromancer", author: "William Gibson", year: "1984" },
  { title: "Herland", author: "Charlotte Perkins Gilman" },
  { title: "Lord of the Flies", author: "William Golding", year: "1954" },
  { title: "The Forever War", author: "Joe Haldeman", year: "1974" },
  {
    title: "The House of the Seven Gables",
    author: "Nathaniel Hawthorne",
    year: "1851",
  },
  {
    title: "Stranger in a Strange Land",
    author: "Robert A Heinlein",
    year: "1961",
  },
  { title: "Dune", author: "Frank L Herbert" },
  { title: "The Glass Bead Game", author: "Herman Hesse", year: "1943" },
  { title: "Riddley Walker", author: "Russell Hoban", year: "1980" },
  { title: "Brave New World", author: "Aldous Huxley", year: "1932" },
  { title: "The Unconsoled", author: "Kazuo Ishiguro", year: "1995" },
  {
    title: "The Haunting of Hill House",
    author: "Shirley Jackson",
    year: "1959",
  },
  { title: "The Turn of the Screw", author: "Henry James", year: "1898" },
  { title: "The Children of Men", author: "PD James", year: "1992" },
  { title: "The Trial", author: "Franz Kafka", year: "1925" },
  { title: "Flowers for Algernon", author: "Daniel Keyes", year: "1959" },
  { title: "The Shining", author: "Stephen King" },
  { title: "The Left Hand of Darkness", author: "Ursula Le Guin" },
  { title: "The Chronicles of Narnia", author: "CS Lewis" },
  { title: "The Monk", author: "Matthew Lewis", year: "1796" },
  { title: "A Voyage to Arcturus", author: "David Lindsay", year: "1920" },
  { title: "Beyond Black", author: "Hilary Mantel", year: "2005" },
  { title: "Only Forward", author: "Michael Marshall Smith", year: "1994" },
  { title: "I Am Legend", author: "Richard Matheson" },
  { title: "The Scar", author: "China Mieville" },
  { title: "Ingenious Pain", author: "Andrew Miller", year: "1997" },
  { title: "A Canticle for Leibowitz", author: "Walter M Miller Jr" },
  { title: "Cloud Atlas", author: "David Mitchell" },
  { title: "Mother London", author: "Michael Moorcock", year: "1988" },
  { title: "News from Nowhere", author: "William Morris", year: "1890" },
  { title: "Beloved", author: "Toni Morrison" },
  { title: "The Wind-Up Bird Chronicle", author: "Haruki Murakami" },
  { title: "The Time Traveler’s Wife", author: "Audrey Niffenegger" },
  { title: "Ringworld", author: "Larry Niven", year: "1970" },
  { title: "Nineteen Eighty-Four", author: "George Orwell", year: "1949" },
  { title: "Fight Club", author: "Chuck Palahniuk" },
  { title: "Nightmare Abbey", author: "Thomas Love Peacock" },

  { title: "The Discworld Series", author: "Terry Pratchett" },
  { title: "The Prestige", author: "Christopher Priest", year: "1995" },
  { title: "His Dark Materials", author: "Philip Pullman" },
  { title: "Gargantua and Pantagruel", author: "Francois Rabelais" },
  { title: "The Mysteries of Udolpho", author: "Ann Radcliffe", year: "1794" },
  { title: "Revelation Space", author: "Alastair Reynolds", year: "2000" },
  {
    title: "The Years of Rice and Salt",
    author: "Kim Stanley Robinson",
    year: "2002",
  },
  {
    title: "Harry Potter and the Philosopher’s Stone",
    author: "JK Rowling",
    year: "1997",
  },
  { title: "Satanic Verses", author: "Salman Rushdie" },
  { title: "The Female Man", author: "Joanna Russ", year: "1975" },
  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupery",
    year: "1943",
  },
  { title: "Blindness", author: "Jose Saramago" },
  { title: "How the Dead Live", author: "Will Self", year: "2000" },
  { title: "Frankenstein", author: "Mary Shelley" },
  { title: "Hyperion", author: "Dan Simmons" },
  { title: "Star Maker", author: "Olaf Stapledon" },
  { title: "Snow Crash", author: "Neal Stephenson", year: "1992" },
  {
    title: "The Strange Case of Dr Jekyll and Mr Hyde",
    author: "Robert Louis Stevenson",
    year: "1886",
  },
  { title: "Dracula", author: "Bram Stoker", year: "1897" },
  { title: "The Hobbit", author: "JRR Tolkien", year: "1937" },
  { title: "The Lord of the Rings", author: "JRR Tolkien", year: "1126" },
  {
    title: "A Connecticut Yankee in King Arthur’s Court",
    author: "Mark Twain",
  },
  { title: "Sirens of Titan", author: "Kurt Vonnegut", year: "1959" },
  { title: "The Castle of Otranto", author: "Horace Walpole", year: "1764" },
  { title: "The Time Machine", author: "HG Wells", year: "1895" },
  { title: "The War of the Worlds", author: "HG Wells", year: "1898" },
  { title: "The Sword in the Stone", author: "TH White" },
  { title: "The Book of the New Sun", author: "Gene Wolfe", year: "1980" },
  { title: "Day of the Triffids", author: "John Wyndham", year: "1951" },
  { title: "We", author: "Yevgeny Zamyatin" },
  { title: "Things Fall Apart", author: "Chinua Achebe", year: "1958" },
  { title: "Go Tell it on the Mountain", author: "James Baldwin" },
  { title: "Uncle Tom’s Cabin", author: "Harriet Beecher Stowe" },
  { title: "Oroonoko, or The Royal Slave", author: "Aphra Behn" },
  { title: "Clayhanger", author: "Arnold Bennett", year: "1910" },
  { title: "Disgrace", author: "JM Coetzee", year: "1999" },

  { title: "White Noise", author: "Don DeLillo" },
  { title: "A Tale of Two Cities", author: "Charles Dickens" },
  { title: "Middlemarch", author: "George Eliot" },
  { title: "The Invisible Man", author: "Ralph Ellison" },
  { title: "A Passage to India", author: "EM Forster", year: "1924" },
  { title: "The Corrections", author: "Jonathan Franzen", year: "2001" },
  { title: "The Recognitions", author: "William Gaddis", year: "1955" },
  { title: "North and South", author: "Elizabeth Gaskell" },
  { title: "The Counterfeiters", author: "Andre Gide" },
  { title: "Les Miserables", author: "Victor Hugo", year: "1862" },
  { title: "A Girl in Winter", author: "Philip Larkin" },
  { title: "The Grass is Singing", author: "Doris Lessing", year: "1950" },
  { title: "Babbitt", author: "Sinclair Lewis" },
  { title: "Absolute Beginners", author: "Colin MacInnes" },
  { title: "Animal Farm", author: "George Orwell" },
  { title: "Midnight’s Children", author: "Salman Rushdie", year: "1981" },
  { title: "The Jungle", author: "Upton Sinclair", year: "1906" },
  { title: "White Teeth", author: "Zadie Smith", year: "2000" },
  { title: "The Grapes of Wrath", author: "John Steinbeck", year: "1939" },
  { title: "The Red Room", author: "August Strindberg" },
  { title: "Vanity Fair", author: "William Makepeace Thackeray" },

  {
    title: "The Last Chronicle of Barset",
    author: "Anthony Trollope",
    year: "1866",
  },
  { title: "The Adventures of Tom Sawyer", author: "Mark Twain", year: "1876" },
  { title: "The Bonfire of the Vanities", author: "Tom Wolfe", year: "1987" },
  { title: "Heart of Darkness", author: "Joseph Conrad" },
  { title: "The Red Badge of Courage", author: "Stephen Crane" },
  { title: "Robinson Crusoe", author: "Daniel Defoe", year: "1719" },
  { title: "The Three Musketeers", author: "Alexandre Dumas", year: "1844" },
  { title: "The Tin Drum", author: "Gunter Grass", year: "1959" },
  { title: "The Kite Runner", author: "Khaled Hosseini", year: "2003" },
  { title: "On the Road", author: "Jack Kerouac", year: "1957" },
  { title: "The Mark of Zorro", author: "Johnston McCulley" },
  {
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    year: "1967",
  },

  { title: "Moby-Dick or, The Whale", author: "Herman Melville" },
  {
    title: "Tales of the South Pacific",
    author: "James Michener",
    year: "1947",
  },
  { title: "Master and Commander", author: "Patrick O’Brian", year: "1969" },
  {
    title: "The Scarlet Pimpernel",
    author: "Baroness Emmuska Orczy",
    year: "1905",
  },
  {
    title: "Zen and the Art of Motorcycle Maintenance",
    author: "Robert Pirsig",
  },
  { title: "Gravity’s Rainbow", author: "Thomas Pynchon" },
  {
    title: "All Quiet on the Western Front",
    author: "Erich Maria Remarque",
    year: "1929",
  },
  {
    title: "Everything is Illuminated",
    author: "Jonathon Safran Foer",
    year: "2002",
  },
  { title: "Ivanhoe", author: "Sir Walter Scott", year: "1819" },
  { title: "Black Beauty", author: "Anna Sewell", year: "1877" },
  { title: "Maus", author: "Art Spiegelman" },
  { title: "Cryptonomicon", author: "Neal Stephenson", year: "1999" },
  { title: "Treasure Island", author: "Robert Louis Stevenson", year: "1883" },
  { title: "Sophie’s Choice", author: "William Styron" },
  { title: "Gulliver’s Travels", author: "Jonathan Swift", year: "1726" },
  { title: "War and Peace", author: "Leo Tolstoy", year: "1865" },
  {
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    year: "1884",
  },
  {
    title: "Around the World in Eighty Days",
    author: "Jules Verne",
    year: "1872",
  },
  { title: "Slaughter-House Five", author: "Kurt Vonnegut", year: "1969" },
];

export { bookdata };
