const bookdata = [
  {
    title: "The Debacle",
    author: "Emile Zola",
    year: "1892",
    cover: "https://covers.openlibrary.org/b/id/13005595-M.jpg",
  },
  {
    title: "Lucky Jim",
    author: "Kingsley Amis",
    year: "1954",
    cover: "https://covers.openlibrary.org/b/id/100313-M.jpg",
  },
  {
    title: "According to Queeney",
    author: "Beryl Bainbridge",
    year: "2001",
    cover: "https://covers.openlibrary.org/b/id/542974-M.jpg",
  },
  {
    title: "Zuleika Dobson",
    author: "Max Beerbohm",
    year: "1911",
    cover: "https://covers.openlibrary.org/b/id/8245404-M.jpg",
  },
  {
    title: "The Uncommon Reader",
    author: "Alan Bennett",
    year: "2007",
    cover: "https://covers.openlibrary.org/b/id/8167155-M.jpg",
  },
  {
    title: "Queen Lucia",
    author: "EF Benson",
    year: "1920",
    cover: "https://covers.openlibrary.org/b/id/5812270-M.jpg",
  },
  {
    title: "The Ascent of Rum Doodle",
    author: "WE Bowman",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The History Man",
    author: "Malcolm Bradbury",
    year: "1975",
    cover: "https://covers.openlibrary.org/b/id/96734-M.jpg",
  },
  {
    title: "Illywhacker",
    author: "Peter Carey",
    year: "1985",
    cover: "https://covers.openlibrary.org/b/id/8315171-M.jpg",
  },
  {
    title: "A Season in Sinji",
    author: "JL Carr",
    year: "1967",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Harpole Report",
    author: "JL Carr",
    year: "1972",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Hearing Trumpet",
    author: "Leonora Carrington",
    year: "1974",
    cover: "https://covers.openlibrary.org/b/id/5298904-M.jpg",
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    year: "1605",
    cover: "https://covers.openlibrary.org/b/id/9655663-M.jpg",
  },
  {
    title: "Just William",
    author: "Richmal Crompton",
    year: "1922",
    cover: "https://covers.openlibrary.org/b/id/199176-M.jpg",
  },
  {
    title: "A Fairy Tale of New York",
    author: "JP Donleavy",
    year: "1973",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Tom Jones",
    author: "Henry Fielding",
    year: "1749",
    cover: "https://covers.openlibrary.org/b/id/12968864-M.jpg",
  },
  {
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    year: "1856",
    cover: "https://covers.openlibrary.org/b/id/12993424-M.jpg",
  },
  {
    title: "Cold Comfort Farm",
    author: "Stella Gibbons",
    year: "1932",
    cover: "https://covers.openlibrary.org/b/id/5374665-M.jpg",
  },
  {
    title: "Dead Souls",
    author: "Nikolai Gogol",
    year: "1842",
    cover: "https://covers.openlibrary.org/b/id/11556418-M.jpg",
  },
  {
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    year: "1908",
    cover: "https://covers.openlibrary.org/b/id/13335427-M.jpg",
  },
  {
    title: "Travels with My Aunt",
    author: "Graham Greene",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/1885455-M.jpg",
  },
  {
    title: "Diary of a Nobody",
    author: "George Grossmith",
    year: "1892",
    cover: "https://covers.openlibrary.org/b/id/8915986-M.jpg",
  },
  {
    title: "Catch-22",
    author: "Joseph Heller",
    year: "1961",
    cover: "https://covers.openlibrary.org/b/id/6468653-M.jpg",
  },
  {
    title: "High Fidelity",
    author: "Nick Hornby",
    year: "1995",
    cover: "https://covers.openlibrary.org/b/id/824359-M.jpg",
  },
  {
    title: "Three Men in a Boat",
    author: "Jerome K Jerome",
    year: "1889",
    cover: "https://covers.openlibrary.org/b/id/8243006-M.jpg",
  },
  {
    title: "Finnegans Wake",
    author: "James Joyce",
    year: "1939",
    cover: "https://covers.openlibrary.org/b/id/6609259-M.jpg",
  },
  {
    title: "Lake Wobegon Days",
    author: "Garrison Keillor",
    year: "1985",
    cover: "https://covers.openlibrary.org/b/id/11663746-M.jpg",
  },
  {
    title: "Death and the Penguin",
    author: "Andrey Kurkov",
    year: "1996",
    cover: "https://covers.openlibrary.org/b/id/915096-M.jpg",
  },
  {
    title: "Changing Places",
    author: "David Lodge",
    year: "1975",
    cover: "https://covers.openlibrary.org/b/id/96531-M.jpg",
  },
  {
    title: "Nice Work",
    author: "David Lodge",
    year: "1988",
    cover: "https://covers.openlibrary.org/b/id/4067603-M.jpg",
  },
  {
    title: "The Towers of Trebizond",
    author: "Rose Macaulay",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/859088-M.jpg",
  },
  {
    title: "England, Their England",
    author: "AG Macdonell",
    year: "1933",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Under the Net",
    author: "Iris Murdoch",
    year: "1954",
    cover: "https://covers.openlibrary.org/b/id/93073-M.jpg",
  },
  {
    title: "La Disparition",
    author: "Georges Perec",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/969759-M.jpg",
  },
  {
    title: "Excellent Women",
    author: "Barbara Pym",
    year: "1952",
    cover: "https://covers.openlibrary.org/b/id/4435559-M.jpg",
  },
  {
    title: "Portnoy\u2019s Complaint",
    author: "Philip Roth",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/6458427-M.jpg",
  },
  {
    title: "Porterhouse Blue",
    author: "Tom Sharpe",
    year: "1974",
    cover: "https://covers.openlibrary.org/b/id/660445-M.jpg",
  },
  {
    title: "The Girls of Slender Means",
    author: "Muriel Spark",
    year: "1963",
    cover: "https://covers.openlibrary.org/b/id/598262-M.jpg",
  },
  {
    title: "White Man Falling",
    author: "Mike Stocks",
    year: "2006",
    cover: "https://covers.openlibrary.org/b/id/6808965-M.jpg",
  },
  {
    title: "Penrod",
    author: "Booth Tarkington",
    year: "1914",
    cover: "https://covers.openlibrary.org/b/id/8244592-M.jpg",
  },
  {
    title: "Barchester Towers",
    author: "Anthony Trollope",
    year: "1857",
    cover: "https://covers.openlibrary.org/b/id/1468666-M.jpg",
  },
  {
    title: "Venus on the Half-Shell",
    author: "Kilgore Trout",
    year: "1975",
    cover: "https://covers.openlibrary.org/b/id/4773645-M.jpg",
  },
  {
    title: "The Witches of Eastwick",
    author: "John Updike",
    year: "1984",
    cover: "https://covers.openlibrary.org/b/id/253747-M.jpg",
  },
  {
    title: "Infinite Jest",
    author: "David Foster Wallace",
    year: "1996",
    cover: "https://covers.openlibrary.org/b/id/8237639-M.jpg",
  },
  {
    title: "Decline and Fall",
    author: "Evelyn Waugh",
    year: "1928",
    cover: "https://covers.openlibrary.org/b/id/417696-M.jpg",
  },
  {
    title: "Anglo-Saxon Attitudes",
    author: "Angus Wilson",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/859168-M.jpg",
  },
  {
    title: "The Inimitable Jeeves",
    author: "PG Wodehouse",
    year: "1923",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Epitaph for a Spy",
    author: "Eric Ambler",
    year: "1938",
    cover: "https://covers.openlibrary.org/b/id/229138-M.jpg",
  },
  {
    title: "The Neon Rain",
    author: "James Lee Burke",
    year: "1987",
    cover: "https://covers.openlibrary.org/b/id/7940445-M.jpg",
  },
  {
    title: "The Tin Roof Blowdown",
    author: "James Lee Burke",
    year: "2007",
    cover: "https://covers.openlibrary.org/b/id/6882397-M.jpg",
  },
  {
    title: "The Thirty-Nine Steps",
    author: "John Buchan",
    year: "1915",
    cover: "https://covers.openlibrary.org/b/id/93020-M.jpg",
  },
  {
    title: "Greenmantle",
    author: "John Buchan",
    year: "1916",
    cover: "https://covers.openlibrary.org/b/id/93023-M.jpg",
  },
  {
    title: "The Big Sleep",
    author: "Raymond Chandler",
    year: "1939",
    cover: "https://covers.openlibrary.org/b/id/7268475-M.jpg",
  },
  {
    title: "A Study in Scarlet",
    author: "Arthur Conan Doyle",
    year: "1887",
    cover: "https://covers.openlibrary.org/b/id/6386927-M.jpg",
  },
  {
    title: "The Manchurian Candidate",
    author: "Richard Condon",
    year: "1959",
    cover: "https://covers.openlibrary.org/b/id/1957843-M.jpg",
  },
  {
    title: "The Secret Agent",
    author: "Joseph Conrad",
    year: "1907",
    cover: "https://covers.openlibrary.org/b/id/8239401-M.jpg",
  },
  {
    title: "The Andromeda Strain",
    author: "Michael Crichton",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/9330577-M.jpg",
  },
  {
    title: "Dead Lagoon",
    author: "Michael Dibdin",
    year: "1994",
    cover: "https://covers.openlibrary.org/b/id/4653723-M.jpg",
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: "1866",
    cover: "https://covers.openlibrary.org/b/id/11227994-M.jpg",
  },
  {
    title: "An American Tragedy",
    author: "Theodore Dreiser",
    year: "1925",
    cover: "https://covers.openlibrary.org/b/id/12728401-M.jpg",
  },
  {
    title: "My Cousin Rachel",
    author: "Daphne du Maurier",
    year: "1951",
    cover: "https://covers.openlibrary.org/b/id/6603165-M.jpg",
  },
  {
    title: "The Name of the Rose",
    author: "Umberto Eco",
    year: "1980",
    cover: "https://covers.openlibrary.org/b/id/10790060-M.jpg",
  },
  {
    title: "American Psycho",
    author: "Bret Easton Ellis",
    year: "1991",
    cover: "https://covers.openlibrary.org/b/id/8401686-M.jpg",
  },
  {
    title: "LA Confidential",
    author: "James Ellroy",
    year: "1990",
    cover: "https://covers.openlibrary.org/b/id/381471-M.jpg",
  },
  {
    title: "The Big Nowhere",
    author: "James Ellroy",
    year: "1988",
    cover: "https://covers.openlibrary.org/b/id/3233404-M.jpg",
  },
  {
    title: "A Quiet Belief in Angels",
    author: "RJ Ellory",
    year: "2007",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Casino Royale",
    author: "Ian Fleming",
    year: "1953",
    cover: "https://covers.openlibrary.org/b/id/5540820-M.jpg",
  },
  {
    title: "The King of Torts",
    author: "John Grisham",
    year: "2003",
    cover: "https://covers.openlibrary.org/b/id/6618007-M.jpg",
  },
  {
    title: "Hangover Square",
    author: "Patrick Hamilton",
    year: "1941",
    cover: "https://covers.openlibrary.org/b/id/12851651-M.jpg",
  },
  {
    title: "The Maltese Falcon",
    author: "Dashiell Hammett",
    year: "1930",
    cover: "https://covers.openlibrary.org/b/id/6668858-M.jpg",
  },
  {
    title: "Tourist Season",
    author: "Carl Hiaasen",
    year: "1986",
    cover: "https://covers.openlibrary.org/b/id/1463622-M.jpg",
  },
  {
    title: "Bones and Silence",
    author: "Reginald Hill",
    year: "1990",
    cover: "https://covers.openlibrary.org/b/id/280393-M.jpg",
  },
  {
    title: "A Rage in Harlem",
    author: "Chester Himes",
    year: "1957",
    cover: "https://covers.openlibrary.org/b/id/8992701-M.jpg",
  },
  {
    title: "Malice Aforethought",
    author: "Francis Iles",
    year: "1931",
    cover: "https://covers.openlibrary.org/b/id/499561-M.jpg",
  },
  {
    title: "Silence of the Grave",
    author: "Arnadur Indridason",
    year: "2001",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Misery",
    author: "Stephen King",
    year: "1987",
    cover: "https://covers.openlibrary.org/b/id/8259296-M.jpg",
  },
  {
    title: "The Jungle Book",
    author: "Rudyard Kipling",
    year: "1894",
    cover: "https://covers.openlibrary.org/b/id/2140514-M.jpg",
  },
  {
    title: "The Constant Gardener",
    author: "John le Carre",
    year: "2001",
    cover: "https://covers.openlibrary.org/b/id/7009431-M.jpg",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: "1960",
    cover: "https://covers.openlibrary.org/b/id/12606502-M.jpg",
  },
  {
    title: "Motherless Brooklyn",
    author: "Jonathan Lethem",
    cover: "https://covers.openlibrary.org/b/id/8261337-M.jpg",
  },
  {
    title: "The Bourne Identity",
    author: "Robert Ludlum",
    cover: "https://covers.openlibrary.org/b/id/499340-M.jpg",
  },
  {
    title: "Cop Hater",
    author: "Ed McBain",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/4088473-M.jpg",
  },
  {
    title: "No Country for Old Men",
    author: "Cormac McCarthy",
    cover: "https://covers.openlibrary.org/b/id/9296899-M.jpg",
  },
  {
    title: "Enduring Love",
    author: "Ian McEwan",
    year: "1997",
    cover: "https://covers.openlibrary.org/b/id/6494444-M.jpg",
  },
  {
    title: "Sidetracked",
    author: "Henning Mankell",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Devil in a Blue Dress",
    author: "Walter Mosley",
    year: "1990",
    cover: "https://covers.openlibrary.org/b/id/477489-M.jpg",
  },
  {
    title: "My Name is Red",
    author: "Orhan Pamuk",
    year: "1998",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Big Blowdown",
    author: "George Pelecanos",
    year: "1996",
    cover: "https://covers.openlibrary.org/b/id/9189621-M.jpg",
  },
  {
    title: "The Godfather",
    author: "Mario Puzo",
    cover: "https://covers.openlibrary.org/b/id/6507069-M.jpg",
  },
  {
    title: "The Crying of Lot 49",
    author: "Thomas Pynchon",
    cover: "https://covers.openlibrary.org/b/id/39754-M.jpg",
  },
  {
    title: "Exit Music",
    author: "Ian Rankin",
    year: "2007",
    cover: "https://covers.openlibrary.org/b/id/6890867-M.jpg",
  },
  {
    title: "Judgment in Stone",
    author: "Ruth Rendell",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Live Flesh",
    author: "Ruth Rendell",
    year: "1986",
    cover: "https://covers.openlibrary.org/b/id/5375111-M.jpg",
  },
  {
    title: "Murder Must Advertise",
    author: "Dorothy Le Sayers",
    year: "1933",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Madman of Bergerac",
    author: "Georges Simenon",
    year: "1932",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Of Mice and Men",
    author: "John Steinbeck",
    year: "1937",
    cover: "https://covers.openlibrary.org/b/id/12703536-M.jpg",
  },
  {
    title: "The League of Frightened Men",
    author: "Rex Stout",
    year: "1935",
    cover: "https://covers.openlibrary.org/b/id/463173-M.jpg",
  },
  {
    title: "The Secret History",
    author: "Donna Tartt",
    year: "1992",
    cover: "https://covers.openlibrary.org/b/id/744854-M.jpg",
  },
  {
    title: "The Daughter of Time",
    author: "Josephine Tey",
    year: "1951",
    cover: "https://covers.openlibrary.org/b/id/6485299-M.jpg",
  },
  {
    title: "Native Son",
    author: "Richard Wright",
    year: "1940",
    cover: "https://covers.openlibrary.org/b/id/10830375-M.jpg",
  },
  {
    title: "Therese Raquin",
    author: "Emile Zola",
    year: "1867",
    cover: "https://covers.openlibrary.org/b/id/7069762-M.jpg",
  },
  {
    title: "The Face of Another",
    author: "Kobo Abe",
    year: "1964",
    cover: "https://covers.openlibrary.org/b/id/229655-M.jpg",
  },
  {
    title: "Little Women",
    author: "Louisa May Alcott",
    year: "1868",
    cover: "https://covers.openlibrary.org/b/id/6795866-M.jpg",
  },
  {
    title: "Cat\u2019s Eye",
    author: "Margaret Atwood",
    cover: "https://covers.openlibrary.org/b/id/12506526-M.jpg",
  },
  {
    title: "The Crow Road",
    author: "Iain Banks",
    year: "1992",
    cover: "https://covers.openlibrary.org/b/id/212875-M.jpg",
  },
  {
    title: "The L Shaped Room",
    author: "Lynne Reid Banks",
    cover: "https://covers.openlibrary.org/b/id/6183239-M.jpg",
  },
  {
    title: "Fun Home",
    author: "Alison Bechdel",
    cover: "https://covers.openlibrary.org/b/id/12366765-M.jpg",
  },
  {
    title: "Malone Dies",
    author: "Samuel Beckett",
    year: "1951",
    cover: "https://covers.openlibrary.org/b/id/10692109-M.jpg",
  },
  {
    title: "Humboldt\u2019s Gift",
    author: "Saul Bellow",
    cover: "https://covers.openlibrary.org/b/id/5411438-M.jpg",
  },
  {
    title: "The Way of All Flesh",
    author: "Samuel Butler",
    year: "1903",
    cover: "https://covers.openlibrary.org/b/id/8243340-M.jpg",
  },
  {
    title: "The Outsider",
    author: "Albert Camus",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Wise Children",
    author: "Angela Carter",
    year: "1991",
    cover: "https://covers.openlibrary.org/b/id/3965976-M.jpg",
  },
  {
    title: "The Professor\u2019s House",
    author: "Willa Cather",
    cover: "https://covers.openlibrary.org/b/id/573461-M.jpg",
  },
  {
    title: "The Awakening",
    author: "Kate Chopin",
    cover: "https://covers.openlibrary.org/b/id/8750241-M.jpg",
  },
  {
    title: "Being Dead",
    author: "Jim Crace",
    year: "1999",
    cover: "https://covers.openlibrary.org/b/id/10158800-M.jpg",
  },
  {
    title: "Great Expectations",
    author: "Charles Dickens",
    cover: "https://covers.openlibrary.org/b/id/13322313-M.jpg",
  },
  {
    title: "My New York Diary",
    author: "Julie Doucet",
    cover: "https://covers.openlibrary.org/b/id/944788-M.jpg",
  },
  {
    title: "Middlesex",
    author: "Jeffrey Eugenides",
    cover: "https://covers.openlibrary.org/b/id/12367196-M.jpg",
  },
  {
    title: "The Sound and the Fury",
    author: "William Faulkner",
    year: "1929",
    cover: "https://covers.openlibrary.org/b/id/8292212-M.jpg",
  },
  {
    title: "The Sportswriter",
    author: "Richard Ford",
    year: "1986",
    cover: "https://covers.openlibrary.org/b/id/419011-M.jpg",
  },
  {
    title: "Howards End",
    author: "EM Forster",
    year: "1910",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    cover: "https://covers.openlibrary.org/b/id/426182-M.jpg",
  },
  {
    title: "A Prayer for Owen Meany",
    author: "John Irving",
    year: "1989",
    cover: "https://covers.openlibrary.org/b/id/5414972-M.jpg",
  },
  {
    title: "The Ambassadors",
    author: "Henry James",
    year: "1903",
    cover: "https://covers.openlibrary.org/b/id/313610-M.jpg",
  },
  {
    title: "The Unfortunates",
    author: "BS Johnson",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "A Portrait of the Artist as a Young Man",
    author: "James Joyce",
    cover: "https://covers.openlibrary.org/b/id/9328410-M.jpg",
  },
  {
    title: "Ulysses",
    author: "James Joyce",
    cover: "https://covers.openlibrary.org/b/id/13136548-M.jpg",
  },
  {
    title: "One Flew Over the Cuckoo\u2019s Nest",
    author: "Ken Kesey",
    cover: "https://covers.openlibrary.org/b/id/9272688-M.jpg",
  },
  {
    title: "Sons and Lovers",
    author: "DH Lawrence",
    year: "1913",
    cover: "https://covers.openlibrary.org/b/id/8246175-M.jpg",
  },
  {
    title: "The Golden Notebook",
    author: "Doris Lessing",
    year: "1962",
    cover: "https://covers.openlibrary.org/b/id/42601-M.jpg",
  },
  {
    title: "Martin Eden",
    author: "Jack London",
    year: "1909",
    cover: "https://covers.openlibrary.org/b/id/9223765-M.jpg",
  },
  {
    title: "Under the Volcano",
    author: "Malcolm Lowry",
    year: "1947",
    cover: "https://covers.openlibrary.org/b/id/4197484-M.jpg",
  },
  {
    title: "Palace Walk",
    author: "Naguib Mahfouz",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/238858-M.jpg",
  },
  {
    title: "The Bluest Eye",
    author: "Toni Morrison",
    year: "1970",
    cover: "https://covers.openlibrary.org/b/id/9255403-M.jpg",
  },
  {
    title: "Who Do You Think You Are?",
    author: "Alice Munro",
    cover: "https://covers.openlibrary.org/b/id/420124-M.jpg",
  },
  {
    title: "The Man Without Qualities",
    author: "Robert Musil",
    year: "1930",
    cover: "https://covers.openlibrary.org/b/id/9156178-M.jpg",
  },
  {
    title: "A House for Mr Biswas",
    author: "VS Naipaul",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Teach Us to Outgrow Our Madness",
    author: "Kezaburo Oe",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Bell Jar",
    author: "Sylvia Plath",
    year: "1963",
    cover: "https://covers.openlibrary.org/b/id/8477115-M.jpg",
  },
  {
    title: "My Name Is Asher Lev",
    author: "Chaim Potok",
    year: "1972",
    cover: "https://covers.openlibrary.org/b/id/12724040-M.jpg",
  },
  {
    title: "The Good Companions",
    author: "JB Priestley",
    year: "1929",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Shipping News",
    author: "E Annie Proulx",
    year: "1993",
    cover: "https://covers.openlibrary.org/b/id/10522593-M.jpg",
  },
  {
    title: "The God of Small Things",
    author: "Arundhati Roy",
    year: "1997",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Catcher in the Rye",
    author: "JD Salinger",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Alberta and Jacob",
    author: "Cora Sandel",
    cover: "https://covers.openlibrary.org/b/id/458012-M.jpg",
  },
  {
    title: "A Suitable Boy",
    author: "Vikram Seth",
    year: "1993",
    cover: "https://covers.openlibrary.org/b/id/911254-M.jpg",
  },
  {
    title: "Unless",
    author: "Carol Shields",
    year: "2002",
    cover: "https://covers.openlibrary.org/b/id/10713534-M.jpg",
  },
  {
    title: "A Thousand Acres",
    author: "Jane Smiley",
    year: "1991",
    cover: "https://covers.openlibrary.org/b/id/744977-M.jpg",
  },
  {
    title: "On Beauty",
    author: "Zadie Smith",
    year: "2005",
    cover: "https://covers.openlibrary.org/b/id/400923-M.jpg",
  },
  {
    title: "East of Eden",
    author: "John Steinbeck",
    cover: "https://covers.openlibrary.org/b/id/11386937-M.jpg",
  },
  {
    title: "Lark Rise to Candleford",
    author: "Flora Thompson",
    year: "1945",
    cover: "https://covers.openlibrary.org/b/id/97882-M.jpg",
  },
  {
    title: "The Blackwater Lightship",
    author: "Colm Toibin",
    year: "1999",
    cover: "https://covers.openlibrary.org/b/id/429026-M.jpg",
  },
  {
    title: "Death in Summer",
    author: "William Trevor",
    year: "1998",
    cover: "https://covers.openlibrary.org/b/id/402227-M.jpg",
  },
  {
    title: "The Rabbit Omnibus",
    author: "John Updike",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Color Purple",
    author: "Alice Walker",
    year: "1982",
    cover: "https://covers.openlibrary.org/b/id/8564628-M.jpg",
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    cover: "https://covers.openlibrary.org/b/id/13255530-M.jpg",
  },
  {
    title: "To the Lighthouse",
    author: "Virginia Woolf",
    year: "1927",
    cover: "https://covers.openlibrary.org/b/id/8231846-M.jpg",
  },
  {
    title: "Swiss Family Robinson",
    author: "Johann David Wyss",
    year: "1812",
    cover: "https://covers.openlibrary.org/b/id/8819908-M.jpg",
  },
  {
    title: "Le Grand Meaulnes",
    author: "Henri Alain-Fournier",
    year: "1913",
    cover: "https://covers.openlibrary.org/b/id/8239494-M.jpg",
  },
  {
    title: "Dom Casmurro Joaquim",
    author: "Maria Machado de Assis",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Northanger Abbey",
    author: "Jane Austen",
    year: "1817",
    cover: "https://covers.openlibrary.org/b/id/12567961-M.jpg",
  },
  {
    title: "Sense and Sensibility",
    author: "Jane Austen",
    year: "1811",
    cover: "https://covers.openlibrary.org/b/id/9278292-M.jpg",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: "1813",
    cover: "https://covers.openlibrary.org/b/id/12648793-M.jpg",
  },
  {
    title: "Mansfield Park",
    author: "Jane Austen",
    year: "1814",
    cover: "https://covers.openlibrary.org/b/id/9278328-M.jpg",
  },
  {
    title: "Giovanni\u2019s Room",
    author: "James Baldwin",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/97395-M.jpg",
  },
  {
    title: "Nightwood",
    author: "Djuna Barnes",
    year: "1936",
    cover: "https://covers.openlibrary.org/b/id/3885176-M.jpg",
  },
  {
    title: "More Die of Heartbreak",
    author: "Saul Bellow",
    year: "1987",
    cover: "https://covers.openlibrary.org/b/id/5409990-M.jpg",
  },
  {
    title: "Lorna Doone",
    author: "RD Blackmore",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Death of the Heart",
    author: "Elizabeth Bowen",
    year: "1938",
    cover: "https://covers.openlibrary.org/b/id/71487-M.jpg",
  },
  {
    title: "The Heat of the Day",
    author: "Elizabeth Bowen",
    year: "1948",
    cover: "https://covers.openlibrary.org/b/id/243851-M.jpg",
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Bronte",
    year: "1847",
    cover: "https://covers.openlibrary.org/b/id/8235363-M.jpg",
  },
  {
    title: "Wuthering Heights",
    author: "Emily Bronte",
    cover: "https://covers.openlibrary.org/b/id/12818862-M.jpg",
  },
  {
    title: "Rubyfruit Jungle",
    author: "Rita Mae Brown",
    year: "1973",
    cover: "https://covers.openlibrary.org/b/id/11444993-M.jpg",
  },
  {
    title: "Breakfast at Tiffany\u2019s",
    author: "Truman Capote",
    cover: "https://covers.openlibrary.org/b/id/100108-M.jpg",
  },
  {
    title: "Oscar and Lucinda",
    author: "Peter Carey",
    year: "1988",
    cover: "https://covers.openlibrary.org/b/id/421810-M.jpg",
  },
  {
    title: "My Antonia",
    author: "Willa Cather",
    year: "1918",
    cover: "https://covers.openlibrary.org/b/id/8369013-M.jpg",
  },
  {
    title: "Rebecca",
    author: "Daphne du Maurier",
    cover: "https://covers.openlibrary.org/b/id/8238729-M.jpg",
  },
  {
    title: "The Mill on the Floss",
    author: "George Eliot",
    year: "1860",
    cover: "https://covers.openlibrary.org/b/id/8236884-M.jpg",
  },
  {
    title: "The Virgin Suicides",
    author: "Jeffrey Eugenides",
    year: "1993",
    cover: "https://covers.openlibrary.org/b/id/287774-M.jpg",
  },
  {
    title: "The Great Gatsby",
    author: "F Scott Fitzgerald",
    cover: "https://covers.openlibrary.org/b/id/10590366-M.jpg",
  },
  {
    title: "Tender is the Night",
    author: "F Scott Fitzgerald",
    cover: "https://covers.openlibrary.org/b/id/6984433-M.jpg",
  },
  {
    title: "The Blue Flower",
    author: "Penelope Fitzgerald",
    year: "1995",
    cover: "https://covers.openlibrary.org/b/id/257175-M.jpg",
  },
  {
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    year: "1856",
    cover: "https://covers.openlibrary.org/b/id/12993424-M.jpg",
  },
  {
    title: "The Good Soldier",
    author: "Ford Madox Ford",
    year: "1915",
    cover: "https://covers.openlibrary.org/b/id/5723677-M.jpg",
  },
  {
    title: "A Room with a View",
    author: "EM Forster",
    year: "1908",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The French Lieutenant\u2019s Woman",
    author: "John Fowles",
    cover: "https://covers.openlibrary.org/b/id/188822-M.jpg",
  },
  {
    title: "The Snow Goose",
    author: "Paul Gallico",
    cover: "https://covers.openlibrary.org/b/id/4574541-M.jpg",
  },
  {
    title: "Far From the Madding Crowd",
    author: "Thomas Hardy",
    year: "1874",
    cover: "https://covers.openlibrary.org/b/id/8237658-M.jpg",
  },
  {
    title: "Tess of the D\u2019Urbervilles",
    author: "Thomas Hardy",
    cover: "https://covers.openlibrary.org/b/id/13109386-M.jpg",
  },
  {
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    year: "1850",
    cover: "https://covers.openlibrary.org/b/id/5654516-M.jpg",
  },
  {
    title: "The Transit of Venus",
    author: "Shirley Hazzard",
    year: "1980",
    cover: "https://covers.openlibrary.org/b/id/4399306-M.jpg",
  },
  {
    title: "The Remains of the Day",
    author: "Kazuo Ishiguro",
    year: "1989",
    cover: "https://covers.openlibrary.org/b/id/95742-M.jpg",
  },
  {
    title: "Portrait of a Lady",
    author: "Henry James",
    year: "1881",
    cover: "https://covers.openlibrary.org/b/id/8236992-M.jpg",
  },
  {
    title: "The Wings of the Dove",
    author: "Henry James",
    year: "1902",
    cover: "https://covers.openlibrary.org/b/id/8241379-M.jpg",
  },
  {
    title: "Zorba the Greek",
    author: "Nikos Kazantzakis",
    cover: "https://covers.openlibrary.org/b/id/13124304-M.jpg",
  },
  {
    title: "Lady Chatterley\u2019s Lover",
    author: "DH Lawrence",
    year: "1126",
    cover: "https://covers.openlibrary.org/b/id/12983362-M.jpg",
  },
  {
    title: "Zami",
    author: "Audre Lorde",
    cover: "https://covers.openlibrary.org/b/id/7102067-M.jpg",
  },
  {
    title: "Death in Venice",
    author: "Thomas Mann",
    year: "1912",
    cover: "https://covers.openlibrary.org/b/id/419785-M.jpg",
  },
  {
    title: "A Heart So White",
    author: "Javier Marias",
    year: "1992",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Of Human Bondage",
    author: "Somerset Maugham",
    year: "1915",
    cover: "https://covers.openlibrary.org/b/id/11996470-M.jpg",
  },
  {
    title: "So Long, See you Tomorrow",
    author: "William Maxwell",
    cover: "https://covers.openlibrary.org/b/id/4393415-M.jpg",
  },
  {
    title: "Atonement",
    author: "Ian McEwan",
    cover: "https://covers.openlibrary.org/b/id/8381043-M.jpg",
  },
  {
    title: "Tropic of Cancer",
    author: "Henry Miller",
    cover: "https://covers.openlibrary.org/b/id/13119236-M.jpg",
  },
  {
    title: "Gone With the Wind",
    author: "Margaret Mitchell",
    cover: "https://covers.openlibrary.org/b/id/8296480-M.jpg",
  },
  {
    title: "The Pursuit of Love",
    author: "Nancy Mitford",
    year: "1945",
    cover: "https://covers.openlibrary.org/b/id/419406-M.jpg",
  },
  {
    title: "Love in a Cold Climate",
    author: "Nancy Mitford",
    cover: "https://covers.openlibrary.org/b/id/92989-M.jpg",
  },
  {
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    cover: "https://covers.openlibrary.org/b/id/13172856-M.jpg",
  },
  {
    title: "The Painter of Signs",
    author: "RK Narayan",
    year: "1977",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Delta of Venus",
    author: "Anais Nin",
    year: "1977",
    cover: "https://covers.openlibrary.org/b/id/8323503-M.jpg",
  },
  {
    title: "The English Patient",
    author: "Michael Ondaatje",
    year: "1992",
    cover: "https://covers.openlibrary.org/b/id/417585-M.jpg",
  },
  {
    title: "Doctor Zhivago",
    author: "Boris Pasternak",
    cover: "https://covers.openlibrary.org/b/id/9414293-M.jpg",
  },
  {
    title: "Manon Lescaut",
    author: "Abbe Prevost",
    year: "1731",
    cover: "https://covers.openlibrary.org/b/id/8236918-M.jpg",
  },
  {
    title: "Wide Sargasso Sea",
    author: "Jean Rhys",
    year: "1966",
    cover: "https://covers.openlibrary.org/b/id/9269373-M.jpg",
  },
  {
    title: "Clarissa",
    author: "Samuel Richardson",
    year: "1748",
    cover: "https://covers.openlibrary.org/b/id/5779843-M.jpg",
  },
  {
    title: "Gilead",
    author: "Marilynne Robinson",
    cover: "https://covers.openlibrary.org/b/id/1472533-M.jpg",
  },
  {
    title: "Bonjour Tristesse",
    author: "Francoise Sagan",
    year: "1954",
    cover: "https://covers.openlibrary.org/b/id/52680-M.jpg",
  },
  {
    title: "The Reader",
    author: "Bernhard Schlink",
    year: "1995",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "I Capture the Castle",
    author: "Dodie Smith",
    year: "1948",
    cover: "https://covers.openlibrary.org/b/id/5080686-M.jpg",
  },
  {
    title: "The Map of Love",
    author: "Ahdaf Soueif",
    cover: "https://covers.openlibrary.org/b/id/243759-M.jpg",
  },
  {
    title: "Valley of the Dolls",
    author: "Jacqueline Susann",
    cover: "https://covers.openlibrary.org/b/id/568844-M.jpg",
  },
  {
    title: "Diary of a Mad Old Man",
    author: "Junichiro Tanizaki",
    cover: "https://covers.openlibrary.org/b/id/746977-M.jpg",
  },
  {
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    year: "1878",
    cover: "https://covers.openlibrary.org/b/id/13180796-M.jpg",
  },
  {
    title: "Breathing Lessons",
    author: "Anne Tyler",
    year: "1988",
    cover: "https://covers.openlibrary.org/b/id/4068258-M.jpg",
  },
  {
    title: "The Accidental Tourist",
    author: "Anne Tyler",
    year: "1985",
    cover: "https://covers.openlibrary.org/b/id/4150580-M.jpg",
  },
  {
    title: "The Age of Innocence",
    author: "Edith Wharton",
    year: "1920",
    cover: "https://covers.openlibrary.org/b/id/11196262-M.jpg",
  },
  {
    title: "Revolutionary Road",
    author: "Richard Yates",
    year: "1961",
    cover: "https://covers.openlibrary.org/b/id/228873-M.jpg",
  },
  {
    title: "The Hitchhikers Guide to the Galaxy",
    author: "Douglas Adams",
    cover: "https://covers.openlibrary.org/b/id/13195551-M.jpg",
  },
  {
    title: "Foundation",
    author: "Isaac Asimov",
    cover: "https://covers.openlibrary.org/b/id/6501822-M.jpg",
  },
  {
    title: "The Blind Assassin",
    author: "Margaret Atwood",
    year: "2000",
    cover: "https://covers.openlibrary.org/b/id/11041760-M.jpg",
  },
  {
    title: "The Handmaid\u2019s Tale",
    author: "Margaret Atwood",
    year: "1985",
    cover: "https://covers.openlibrary.org/b/id/8231851-M.jpg",
  },
  {
    title: "The Drowned World",
    author: "JG Ballard",
    year: "1962",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Crash",
    author: "JG Ballard",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Millennium People",
    author: "JG Ballard",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Wasp Factory",
    author: "Iain Banks",
    year: "1984",
    cover: "https://covers.openlibrary.org/b/id/427635-M.jpg",
  },
  {
    title: "Consider Phlebas",
    author: "Iain M Banks",
    year: "1987",
    cover: "https://covers.openlibrary.org/b/id/11208887-M.jpg",
  },
  {
    title: "Weaveworld",
    author: "Clive Barker",
    year: "1987",
    cover: "https://covers.openlibrary.org/b/id/476274-M.jpg",
  },
  {
    title: "Darkmans",
    author: "Nicola Barker",
    cover: "https://covers.openlibrary.org/b/id/5316813-M.jpg",
  },
  {
    title: "Vathek",
    author: "William Beckford",
    year: "1786",
    cover: "https://covers.openlibrary.org/b/id/5892210-M.jpg",
  },
  {
    title: "The Stars My Destination",
    author: "Alfred Bester",
    year: "1956",
    cover: "https://covers.openlibrary.org/b/id/911114-M.jpg",
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    cover: "https://covers.openlibrary.org/b/id/12993656-M.jpg",
  },
  {
    title: "Rogue Moon",
    author: "Algis Budrys",
    year: "1960",
    cover: "https://covers.openlibrary.org/b/id/5437017-M.jpg",
  },
  {
    title: "The Coming Race",
    author: "EGEL Bulwer-Lytton",
    year: "1871",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "A Clockwork Orange",
    author: "Anthony Burgess",
    cover: "https://covers.openlibrary.org/b/id/13151224-M.jpg",
  },
  {
    title: "A Princess of Mars",
    author: "Edgar Rice Burroughs",
    year: "1912",
    cover: "https://covers.openlibrary.org/b/id/6553811-M.jpg",
  },
  {
    title: "Naked Lunch",
    author: "William Burroughs",
    year: "1959",
    cover: "https://covers.openlibrary.org/b/id/9788627-M.jpg",
  },
  {
    title: "Kindred",
    author: "Octavia Butler",
    cover: "https://covers.openlibrary.org/b/id/8745330-M.jpg",
  },
  {
    title: "Erewhon",
    author: "Samuel Butler",
    year: "1872",
    cover: "https://covers.openlibrary.org/b/id/8231422-M.jpg",
  },
  {
    title: "The Baron in the Trees",
    author: "Italo Calvino",
    cover: "https://covers.openlibrary.org/b/id/12402320-M.jpg",
  },
  {
    title: "The Man who was Thursday",
    author: "GK Chesterton",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Childhood\u2019s End",
    author: "Arthur C Clarke",
    cover: "https://covers.openlibrary.org/b/id/210200-M.jpg",
  },
  {
    title: "Hello Summer, Goodbye",
    author: "Michael G Coney",
    year: "1975",
    cover: "https://covers.openlibrary.org/b/id/12869422-M.jpg",
  },
  {
    title: "House of Leaves",
    author: "Mark Danielewski",
    year: "2000",
    cover: "https://covers.openlibrary.org/b/id/6450442-M.jpg",
  },
  {
    title: "American Gods",
    author: "Neil Gaiman",
    year: "2001",
    cover: "https://covers.openlibrary.org/b/id/8494659-M.jpg",
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    year: "1984",
    cover: "https://covers.openlibrary.org/b/id/283860-M.jpg",
  },
  {
    title: "Herland",
    author: "Charlotte Perkins Gilman",
    cover: "https://covers.openlibrary.org/b/id/448130-M.jpg",
  },
  {
    title: "Lord of the Flies",
    author: "William Golding",
    year: "1954",
    cover: "https://covers.openlibrary.org/b/id/8684447-M.jpg",
  },
  {
    title: "The Forever War",
    author: "Joe Haldeman",
    year: "1974",
    cover: "https://covers.openlibrary.org/b/id/10693768-M.jpg",
  },
  {
    title: "Dune",
    author: "Frank L Herbert",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Glass Bead Game",
    author: "Herman Hesse",
    year: "1943",
    cover: "https://covers.openlibrary.org/b/id/11547809-M.jpg",
  },
  {
    title: "Riddley Walker",
    author: "Russell Hoban",
    year: "1980",
    cover: "https://covers.openlibrary.org/b/id/8510440-M.jpg",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    year: "1932",
    cover: "https://covers.openlibrary.org/b/id/8231823-M.jpg",
  },
  {
    title: "The Unconsoled",
    author: "Kazuo Ishiguro",
    year: "1995",
    cover: "https://covers.openlibrary.org/b/id/5311753-M.jpg",
  },
  {
    title: "The Turn of the Screw",
    author: "Henry James",
    year: "1898",
    cover: "https://covers.openlibrary.org/b/id/8237598-M.jpg",
  },
  {
    title: "The Children of Men",
    author: "PD James",
    year: "1992",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Trial",
    author: "Franz Kafka",
    year: "1925",
    cover: "https://covers.openlibrary.org/b/id/12547005-M.jpg",
  },
  {
    title: "Flowers for Algernon",
    author: "Daniel Keyes",
    year: "1959",
    cover: "https://covers.openlibrary.org/b/id/12947700-M.jpg",
  },
  {
    title: "The Shining",
    author: "Stephen King",
    cover: "https://covers.openlibrary.org/b/id/7013717-M.jpg",
  },
  {
    title: "The Left Hand of Darkness",
    author: "Ursula Le Guin",
    cover: "https://covers.openlibrary.org/b/id/12375574-M.jpg",
  },
  {
    title: "The Chronicles of Narnia",
    author: "CS Lewis",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Monk",
    author: "Matthew Lewis",
    year: "1796",
    cover: "https://covers.openlibrary.org/b/id/6997946-M.jpg",
  },
  {
    title: "A Voyage to Arcturus",
    author: "David Lindsay",
    year: "1920",
    cover: "https://covers.openlibrary.org/b/id/574402-M.jpg",
  },
  {
    title: "Beyond Black",
    author: "Hilary Mantel",
    year: "2005",
    cover: "https://covers.openlibrary.org/b/id/8311695-M.jpg",
  },
  {
    title: "Only Forward",
    author: "Michael Marshall Smith",
    year: "1994",
    cover: "https://covers.openlibrary.org/b/id/372870-M.jpg",
  },
  {
    title: "I Am Legend",
    author: "Richard Matheson",
    cover: "https://covers.openlibrary.org/b/id/911109-M.jpg",
  },
  {
    title: "The Scar",
    author: "China Mieville",
    cover: "https://covers.openlibrary.org/b/id/210923-M.jpg",
  },
  {
    title: "Ingenious Pain",
    author: "Andrew Miller",
    year: "1997",
    cover: "https://covers.openlibrary.org/b/id/2397649-M.jpg",
  },
  {
    title: "A Canticle for Leibowitz",
    author: "Walter M Miller Jr",
    cover: "https://covers.openlibrary.org/b/id/39419-M.jpg",
  },
  {
    title: "Cloud Atlas",
    author: "David Mitchell",
    cover: "https://covers.openlibrary.org/b/id/6714077-M.jpg",
  },
  {
    title: "Mother London",
    author: "Michael Moorcock",
    year: "1988",
    cover: "https://covers.openlibrary.org/b/id/428196-M.jpg",
  },
  {
    title: "News from Nowhere",
    author: "William Morris",
    year: "1890",
    cover: "https://covers.openlibrary.org/b/id/4529814-M.jpg",
  },
  {
    title: "Beloved",
    author: "Toni Morrison",
    cover: "https://covers.openlibrary.org/b/id/8261367-M.jpg",
  },
  {
    title: "The Wind-Up Bird Chronicle",
    author: "Haruki Murakami",
    cover: "https://covers.openlibrary.org/b/id/12976127-M.jpg",
  },
  {
    title: "The Time Traveler\u2019s Wife",
    author: "Audrey Niffenegger",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Ringworld",
    author: "Larry Niven",
    year: "1970",
    cover: "https://covers.openlibrary.org/b/id/6459520-M.jpg",
  },
  {
    title: "Nineteen Eighty-Four",
    author: "George Orwell",
    year: "1949",
    cover: "https://covers.openlibrary.org/b/id/9267242-M.jpg",
  },
  {
    title: "Fight Club",
    author: "Chuck Palahniuk",
    cover: "https://covers.openlibrary.org/b/id/7890578-M.jpg",
  },
  {
    title: "Nightmare Abbey",
    author: "Thomas Love Peacock",
    cover: "https://covers.openlibrary.org/b/id/1956635-M.jpg",
  },
  {
    title: "The Discworld Series",
    author: "Terry Pratchett",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Prestige",
    author: "Christopher Priest",
    year: "1995",
    cover: "https://covers.openlibrary.org/b/id/3850762-M.jpg",
  },
  {
    title: "His Dark Materials",
    author: "Philip Pullman",
    cover: "https://covers.openlibrary.org/b/id/12474447-M.jpg",
  },
  {
    title: "Gargantua and Pantagruel",
    author: "Francois Rabelais",
    cover: "https://covers.openlibrary.org/b/id/9176313-M.jpg",
  },
  {
    title: "The Mysteries of Udolpho",
    author: "Ann Radcliffe",
    year: "1794",
    cover: "https://covers.openlibrary.org/b/id/11796528-M.jpg",
  },
  {
    title: "Revelation Space",
    author: "Alastair Reynolds",
    year: "2000",
    cover: "https://covers.openlibrary.org/b/id/911071-M.jpg",
  },
  {
    title: "Satanic Verses",
    author: "Salman Rushdie",
    cover: "https://covers.openlibrary.org/b/id/8312209-M.jpg",
  },
  {
    title: "The Female Man",
    author: "Joanna Russ",
    year: "1975",
    cover: "https://covers.openlibrary.org/b/id/448143-M.jpg",
  },
  {
    title: "Blindness",
    author: "Jose Saramago",
    cover: "https://covers.openlibrary.org/b/id/115428-M.jpg",
  },
  {
    title: "How the Dead Live",
    author: "Will Self",
    year: "2000",
    cover: "https://covers.openlibrary.org/b/id/568336-M.jpg",
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    cover: "https://covers.openlibrary.org/b/id/10872750-M.jpg",
  },
  {
    title: "Hyperion",
    author: "Dan Simmons",
    cover: "https://covers.openlibrary.org/b/id/484851-M.jpg",
  },
  {
    title: "Star Maker",
    author: "Olaf Stapledon",
    cover: "https://covers.openlibrary.org/b/id/911107-M.jpg",
  },
  {
    title: "Snow Crash",
    author: "Neal Stephenson",
    year: "1992",
    cover: "https://covers.openlibrary.org/b/id/7004665-M.jpg",
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    year: "1897",
    cover: "https://covers.openlibrary.org/b/id/106193-M.jpg",
  },
  {
    title: "The Hobbit",
    author: "JRR Tolkien",
    year: "1937",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Lord of the Rings",
    author: "JRR Tolkien",
    year: "1126",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "Sirens of Titan",
    author: "Kurt Vonnegut",
    year: "1959",
    cover: "https://covers.openlibrary.org/b/id/1364468-M.jpg",
  },
  {
    title: "The Castle of Otranto",
    author: "Horace Walpole",
    year: "1764",
    cover: "https://covers.openlibrary.org/b/id/6468730-M.jpg",
  },
  {
    title: "The Time Machine",
    author: "HG Wells",
    year: "1895",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The War of the Worlds",
    author: "HG Wells",
    year: "1898",
    cover: "https://covers.openlibrary.org/b/id/12620359-M.jpg",
  },
  {
    title: "The Sword in the Stone",
    author: "TH White",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "The Book of the New Sun",
    author: "Gene Wolfe",
    year: "1980",
    cover: "https://covers.openlibrary.org/b/id/11305529-M.jpg",
  },
  {
    title: "Day of the Triffids",
    author: "John Wyndham",
    year: "1951",
    cover: "https://covers.openlibrary.org/b/id/535027-M.jpg",
  },
  {
    title: "We",
    author: "Yevgeny Zamyatin",
    cover: "https://covers.openlibrary.org/b/id/11566742-M.jpg",
  },
  {
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    year: "1958",
    cover: "https://covers.openlibrary.org/b/id/12816943-M.jpg",
  },
  {
    title: "Go Tell it on the Mountain",
    author: "James Baldwin",
    cover: "https://covers.openlibrary.org/b/id/97426-M.jpg",
  },
  {
    title: "Uncle Tom\u2019s Cabin",
    author: "Harriet Beecher Stowe",
    cover: "https://covers.openlibrary.org/b/id/12728198-M.jpg",
  },
  {
    title: "Oroonoko, or The Royal Slave",
    author: "Aphra Behn",
    cover: "https://covers.openlibrary.org/b/id/12556984-M.jpg",
  },
  {
    title: "Clayhanger",
    author: "Arnold Bennett",
    year: "1910",
    cover: "https://covers.openlibrary.org/b/id/2753558-M.jpg",
  },
  {
    title: "Disgrace",
    author: "JM Coetzee",
    year: "1999",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "White Noise",
    author: "Don DeLillo",
    cover: "https://covers.openlibrary.org/b/id/94015-M.jpg",
  },
  {
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    cover: "https://covers.openlibrary.org/b/id/13301713-M.jpg",
  },
  {
    title: "Middlemarch",
    author: "George Eliot",
    cover: "https://covers.openlibrary.org/b/id/295293-M.jpg",
  },
  {
    title: "The Invisible Man",
    author: "Ralph Ellison",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
  {
    title: "A Passage to India",
    author: "EM Forster",
    year: "1924",
    cover: "https://covers.openlibrary.org/b/id/97064-M.jpg",
  },
  {
    title: "The Corrections",
    author: "Jonathan Franzen",
    year: "2001",
    cover: "https://covers.openlibrary.org/b/id/9273701-M.jpg",
  },
  {
    title: "The Recognitions",
    author: "William Gaddis",
    year: "1955",
    cover: "https://covers.openlibrary.org/b/id/12578033-M.jpg",
  },
  {
    title: "North and South",
    author: "Elizabeth Gaskell",
    cover: "https://covers.openlibrary.org/b/id/8242253-M.jpg",
  },
  {
    title: "The Counterfeiters",
    author: "Andre Gide",
    cover: "https://covers.openlibrary.org/b/id/254180-M.jpg",
  },
  {
    title: "Les Miserables",
    author: "Victor Hugo",
    year: "1862",
    cover: "https://covers.openlibrary.org/b/id/12721865-M.jpg",
  },
  {
    title: "A Girl in Winter",
    author: "Philip Larkin",
    cover: "https://covers.openlibrary.org/b/id/4485141-M.jpg",
  },
  {
    title: "The Grass is Singing",
    author: "Doris Lessing",
    year: "1950",
    cover: "https://covers.openlibrary.org/b/id/296181-M.jpg",
  },
  {
    title: "Babbitt",
    author: "Sinclair Lewis",
    cover: "https://covers.openlibrary.org/b/id/6376827-M.jpg",
  },
  {
    title: "Absolute Beginners",
    author: "Colin MacInnes",
    cover: "https://covers.openlibrary.org/b/id/6781763-M.jpg",
  },
  {
    title: "Animal Farm",
    author: "George Orwell",
    cover: "https://covers.openlibrary.org/b/id/11261770-M.jpg",
  },
  {
    title: "Midnight\u2019s Children",
    author: "Salman Rushdie",
    year: "1981",
    cover: "https://covers.openlibrary.org/b/id/8346713-M.jpg",
  },
  {
    title: "The Jungle",
    author: "Upton Sinclair",
    year: "1906",
    cover: "https://covers.openlibrary.org/b/id/8231790-M.jpg",
  },
  {
    title: "White Teeth",
    author: "Zadie Smith",
    year: "2000",
    cover: "https://covers.openlibrary.org/b/id/146183-M.jpg",
  },
  {
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    year: "1939",
    cover: "https://covers.openlibrary.org/b/id/12715902-M.jpg",
  },
  {
    title: "The Red Room",
    author: "August Strindberg",
    cover: "https://covers.openlibrary.org/b/id/5828202-M.jpg",
  },
  {
    title: "Vanity Fair",
    author: "William Makepeace Thackeray",
    cover: "https://covers.openlibrary.org/b/id/417329-M.jpg",
  },
  {
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    year: "1876",
    cover: "https://covers.openlibrary.org/b/id/7103517-M.jpg",
  },
  {
    title: "The Bonfire of the Vanities",
    author: "Tom Wolfe",
    year: "1987",
    cover: "https://covers.openlibrary.org/b/id/10548223-M.jpg",
  },
  {
    title: "Heart of Darkness",
    author: "Joseph Conrad",
    cover: "https://covers.openlibrary.org/b/id/5048643-M.jpg",
  },
  {
    title: "The Red Badge of Courage",
    author: "Stephen Crane",
    cover: "https://covers.openlibrary.org/b/id/8236915-M.jpg",
  },
  {
    title: "Robinson Crusoe",
    author: "Daniel Defoe",
    year: "1719",
    cover: "https://covers.openlibrary.org/b/id/8783768-M.jpg",
  },
  {
    title: "The Three Musketeers",
    author: "Alexandre Dumas",
    year: "1844",
    cover: "https://covers.openlibrary.org/b/id/9199825-M.jpg",
  },
  {
    title: "The Tin Drum",
    author: "Gunter Grass",
    year: "1959",
    cover: "https://covers.openlibrary.org/b/id/419922-M.jpg",
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    year: "2003",
    cover: "https://covers.openlibrary.org/b/id/9248224-M.jpg",
  },
  {
    title: "On the Road",
    author: "Jack Kerouac",
    year: "1957",
    cover: "https://covers.openlibrary.org/b/id/34655-M.jpg",
  },
  {
    title: "The Mark of Zorro",
    author: "Johnston McCulley",
    cover: "https://covers.openlibrary.org/b/id/111501-M.jpg",
  },
  {
    title: "Moby-Dick or, The Whale",
    author: "Herman Melville",
    cover: "https://covers.openlibrary.org/b/id/11757200-M.jpg",
  },
  {
    title: "Master and Commander",
    author: "Patrick O\u2019Brian",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/3697943-M.jpg",
  },
  {
    title: "Gravity\u2019s Rainbow",
    author: "Thomas Pynchon",
    cover: "https://covers.openlibrary.org/b/id/97894-M.jpg",
  },
  {
    title: "Ivanhoe",
    author: "Sir Walter Scott",
    year: "1819",
    cover: "https://covers.openlibrary.org/b/id/834686-M.jpg",
  },
  {
    title: "Black Beauty",
    author: "Anna Sewell",
    year: "1877",
    cover: "https://covers.openlibrary.org/b/id/5007492-M.jpg",
  },
  {
    title: "Maus",
    author: "Art Spiegelman",
    cover: "https://covers.openlibrary.org/b/id/10210168-M.jpg",
  },
  {
    title: "Cryptonomicon",
    author: "Neal Stephenson",
    year: "1999",
    cover: "https://covers.openlibrary.org/b/id/8310121-M.jpg",
  },
  {
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    year: "1883",
    cover: "https://covers.openlibrary.org/b/id/8229197-M.jpg",
  },
  {
    title: "Sophie\u2019s Choice",
    author: "William Styron",
    cover: "https://covers.openlibrary.org/b/id/6616199-M.jpg",
  },
  {
    title: "Gulliver\u2019s Travels",
    author: "Jonathan Swift",
    year: "1726",
    cover: "https://covers.openlibrary.org/b/id/12717083-M.jpg",
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: "1865",
    cover: "https://covers.openlibrary.org/b/id/13264387-M.jpg",
  },
  {
    title: "Slaughter-House Five",
    author: "Kurt Vonnegut",
    year: "1969",
    cover: "https://covers.openlibrary.org/b/id/None-M.jpg",
  },
];

export { bookdata };
